### ISSUE TITLE
Issues with installing package with newer version of python

### ISSUE THREAD

**Issue by mbestipa** [jvkersch/tmtools#10]
Hi there.
Thank you for this useful package! I see that 3.10 wheels have been built, however I cannot install them using pip:
```console
pyenv local 3.10.8
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install tmtools
```
Gives the following error:

ERROR: Could not find a version that satisfies the requirement tmtools (from versions: none)
ERROR: No matching distribution found for tmtools

Would it be an idea to setup a dependabot/ GitHub action to automatically build the library for different python versions?

**Comment by mbestipa** [comment]
Hey Doris, I'm on macOS/python3.10, indeed the wheels were not there, I saw that you built them for 3.11 as well, thanks for that.

Regarding the GitHub action, I've opened a PR as an example of what this could look like. https://github.com/jvkersch/tmtools/pull/16

**Comment by jvkersch** [comment]
@mbestipa The new wheels are now on PyPI, so I'll close this. Thanks again for bringing my attention to this and for providing the initial fix.
