### ISSUE TITLE
Expose resulting sequence alignment from TMAlign

### ISSUE THREAD

**Issue by cvigilv** [jvkersch/tmtools#33]
Hi! Thanks for the awesome work. Would like to know if you could possibly add the sequence alignment generated from the structural alignment as an output to the TMResult object. That way we can use that information to compute RMSD with external methods or other downstream tasks.

**Comment by jvkersch** [comment]
This would be good to have, I agree. I have to pour over the TMalign code for a bit to see how difficult this would be. In the meantime, if you have an idea of how to achieve this, let me know.

**Comment by cvigilv** [comment]
Great! Will give a look at the code and see if I can give you a help. Thanks in advance!

**Comment by cvigilv** [comment]
Related to #38, this could also include exposing the resulting sequence alignment.

**Comment by cvigilv** [comment]
Closing to avoid overlaps and dispersed dialog regarding this feature.

**Comment by jvkersch** [comment]
@cvigilv I would prefer keeping this open to indicate that it hasn't been addressed yet.
