### ISSUE TITLE
MMCIF support

### ISSUE THREAD

**Issue by cvigilv** [jvkersch/tmtools#34]
Hi! The PDB format is starting to be moved out of the way in preference of MMCIF. Could I implement some support for this format as its natively supported by TMAlign?

**Comment by jvkersch** [comment]
@cvigilv That sounds like a good idea, but I would be weary of introducing a tight coupling between a particular format and the alignment code itself. So before we commit to this, a few questions:

- Is there any supplemental information in a typical mmCIF file (beyond the residues and the sequence) that allows TMalign to work better?
- Could we introduce a utility function to read the required data from the mmCIF and pass it into the TMalign algorithm?

**Comment by cvigilv** [comment]
> Is there any supplemental information in a typical mmCIF file (beyond the residues and the sequence) that allows TMalign to work better?

Not really, just a more modern filetype that is robust and easier to parse. Generally speaking, this isn't a problem since biopython has support for parsing this kind of files.

> Could we introduce a utility function to read the required data from the mmCIF and pass it into the TMalign algorithm?

Yes! I already did a small prototype overwriting the `get_structure` function that uses the MMCIFParser in place of the PDBParser and it works out of the gate. Take a look:
~~~python
def get_structure(fname):
    fname = str(fname)
    b = os.path.basename(fname)
    sname, _ = os.path.splitext(b)

    parser = MMCIFParser()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        structure = parser.get_structure(sname, fname)

    return structure
~~~

What I think I could do is implement an argument for the protein structure format (lets call it `format`) and receive as an argument one of the following: `pdb` (if structure file is a PDB), `cif` ((if structure file is a MMCIF) or `auto` (default behaviour, select PDB or MMCIF parser based on file extension).

**Comment by jvkersch** [comment]
> What I think I could do is implement an argument for the protein structure format (lets call it `format`) and receive as an argument one of the following: `pdb` (if structure file is a PDB), `cif` ((if structure file is a MMCIF) or `auto` (default behaviour, select PDB or MMCIF parser based on file extension).

This sounds like a good approach. I would maybe just make the `format` argument optional and default to `"pdb"` for now, and omit the `"auto"` option, so that the user needs to specify the format. This is similar to how BioPython also forces users to distinguish between fasta and fastq files, etc.

**Comment by jvkersch** [comment]
> What I think I could do is implement an argument for the protein structure format (lets call it `format`) and receive as an argument one of the following: `pdb` (if structure file is a PDB), `cif` ((if structure file is a MMCIF) or `auto` (default behaviour, select PDB or MMCIF parser based on file extension).

This sounds like a good approach. I would maybe just make the `format` argument optional and default to `"pdb"` for now, and omit the `"auto"` option, so that the user needs to specify the format. This is similar to how BioPython also forces users to distinguish between fasta and fastq files, etc.

**Comment by cvigilv** [comment]
Great! Will wrap up the PR and send it your way
