### ISSUE TITLE
Development help

### ISSUE THREAD

**Issue by cvigilv** [jvkersch/tmtools#36]
Hi! 

Could you give me a small description on how to build/install the local version of the package to test everything. Also, could you include how you run unit tests for this, I'm only familiar with the pytest package and haven't been able to test the PR I'm preparing.

Thanks in advance!

**Comment by jvkersch** [comment]
@cvigilv I've opened https://github.com/jvkersch/tmtools/pull/40 with a description of how the test suite works. Basically, it's just the standard Python unittest framework. Does this help you get started with testing?

> how to build/install the local version of the package

Were you able to `pip install -e . -v` to install the package in editable mode?

**Comment by cvigilv** [comment]
I was able to install it with the mentioned command, but didn't know how to test. Just looked at the PR and it seems like a good idea to add that information to make it clearer how to proceed.
