### ISSUE TITLE
Release version 0.2

### ISSUE THREAD

**Issue by cvigilv** [jvkersch/tmtools#42]
Hi! Just wanted to ask for the possibility to push the latest changes to pypi to make use of them in some projects I'm working on. 

Thanks in advance!

**Comment by jvkersch** [comment]
Absolutely! Thanks for all the hard work on the package. I'm currently traveling but I think we can get the remaining PRs in and the package released by the end of the week.

**Comment by jvkersch** [comment]
To-do:

- [ ] Merge #39
- [ ]

**Comment by cvigilv** [comment]
Thanks!

**Comment by jvkersch** [comment]
@cvigilv Version 0.2 is now available from pypi:
```
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tmtools
>>> tmtools.__version__
'0.2.0'
```

I'll close this issue as finished, if any issues arise with the released version or if you have other feature requests, don't hesitate to open an issue. And thanks for all the work in improving the package!
