### ISSUE TITLE
Which one is the target protein, and what is the TM-score?

### ISSUE THREAD

**Issue by smiles724** [jvkersch/tmtools#9]
Hi, thanks for providing this useful toolkit.

However, I have some confusion that needs your help. In your tutorial, `tm_align` accepts two inputs. But which one is the target and the other is the template (coord1 vs. coord2)? Besides, you output `tm_norm_chain1` and `tm_norm_chain2`. Are they all TM-scores?

I am new to TM-score and the question above mentioned may sound naive.

**Comment by ErikHartman** [comment]
`tm_norm_chain1` and `tm_norm_chain2` are the results when normalizing on the different chain lengths. If your proteins are of the same lengths these will be equivalent.

**Comment by jvkersch** [comment]
@smiles724 The explanation provided by @ErikHartman is correct. I have tried to describe that in the Python docstrings (see #30).
